# $Id: makefile,v 1.1.5.1 2013-01-11 20:23:44 mathomp4 Exp $ 

ALL: build_here

LOCDIR   = src/epilogue

include $(ESMF_DIR)/makefile


DIRS     =	src tests

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



