#!/bin/csh

gxps -c -i $3/$1.moist1.$2.out -o $3/$1.moist1.$2.ps
gxps -c -i $3/$1.moist2.$2.out -o $3/$1.moist2.$2.ps
gxps    -i $3/$1.moist3.$2.out -o $3/$1.moist3.$2.ps
gxps -c -i $3/$1.moist_reff.$2.out -o $3/$1.moist_reff.$2.ps

convert -seed 1 -rotate 90 -density 90x90 $3/$1.moist1.$2.ps  $3/moist1.$2.gif
convert -seed 1 -rotate 90 -density 90x90 $3/$1.moist2.$2.ps  $3/moist2.$2.gif
convert -seed 1 -rotate 90 -density 90x90 $3/$1.moist3.$2.ps  $3/moist3.$2.gif
convert -seed 1 -rotate 90 -density 90x90 $3/$1.moist_reff.$2.ps  $3/moist_reff.$2.gif

/bin/rm    $3/$1.moist1.$2.out  $3/$1.moist1.$2.ps
/bin/rm    $3/$1.moist2.$2.out  $3/$1.moist2.$2.ps
/bin/rm    $3/$1.moist3.$2.out  $3/$1.moist3.$2.ps
/bin/rm    $3/$1.moist_reff.$2.out  $3/$1.moist_reff.$2.ps


