!                           DISCLAIMER
!
!   This file was generated by TAF version 1.9.22
!
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
!
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
!
module     adtimingmodule
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.9.22  **
!******************************************************************
!******************************************************************
!==============================================
! referencing used modules
!==============================================
use timingmodule

!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare derived type definitions
!==============================================
type adtms
  real :: adusr
  real :: adsys
end type

!==============================================
! declare derived type variables
!==============================================
type(adtms), private :: adaccum(nblks)
type(adtms), private :: adlast(nblks)

!==============================================
! generic interface blocks
!==============================================
interface operator( + )
  module procedure adtms_add
end interface

interface assignment(=)
  module procedure adtms_ass
end interface

contains
subroutine adtimingmodule_constructor
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.9.22  **
!******************************************************************
!******************************************************************
!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!----------------------------------------------
! RESET ADJOINT MODULE VARIABLES
!----------------------------------------------
adaccum(:) = adtms(0.,0.)
adlast(:) = adtms(0.,0.)

end subroutine adtimingmodule_constructor


function   adtms_add( a, b )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.9.22  **
!******************************************************************
!******************************************************************
!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare arguments
!==============================================
type(adtms), intent(in) :: a
type(adtms) :: adtms_add
type(adtms), intent(in) :: b

adtms_add%adusr = a%adusr+b%adusr
adtms_add%adsys = a%adsys+b%adsys
end function   adtms_add


subroutine adtms_ass( a, b )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 1.9.22  **
!******************************************************************
!******************************************************************
!==============================================
! all entries are defined explicitly
!==============================================
implicit none

!==============================================
! declare arguments
!==============================================
type(adtms), intent(out) :: a
type(adtms), intent(in) :: b

a%adusr = b%adusr
a%adsys = b%adsys
end subroutine adtms_ass


end module     adtimingmodule


