!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'O3PPMV',  &
        LONG_NAME          = 'ozone_volume_mixing_ratio_in_ppm',  &
        UNITS              = 'ppmv', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'OX_TEND',  &
        LONG_NAME          = 'tendency_of_odd_oxygen_mixing_ratio_due_to_chemistry',  &
        UNITS              = 'kg kg-1 s-1', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddExportSpec(GC,  &
        SHORT_NAME         = 'H2O_TEND',  &
        LONG_NAME          = 'tendency_of_water_vapor_mixing_ratio_due_to_chemistry',  &
        UNITS              = 'kg kg-1 s-1', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)

