!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!

      call MAPL_GetPointer ( IMPORT, PS1,  'PS1', RC=STATUS )
      VERIFY_(STATUS)
      call MAPL_GetPointer ( IMPORT, PS2,  'PS2', RC=STATUS )
      VERIFY_(STATUS)
      call MAPL_GetPointer ( IMPORT, U,  'U', RC=STATUS )
      VERIFY_(STATUS)
      call MAPL_GetPointer ( IMPORT, V,  'V', RC=STATUS )
      VERIFY_(STATUS)
