!                          -------------------
!                          W  A  R  N  I  N  G
!                          -------------------
!
!   This code fragment is automatically generated by mapl_acg.
!   Please DO NOT edit it. Any modification made in here will be overwritten
!   next time this file is auto-generated. Instead, enter your additions
!   or deletions in the .rc file. 
!


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_NO',  &
        LONG_NAME          = 'NO',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
        FRIENDLYTO         = 'DYNAMICS:TURBULENCE:T',    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_O3',  &
        LONG_NAME          = 'O3',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
        FRIENDLYTO         = 'DYNAMICS:TURBULENCE:MOIST',    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_PAN',  &
        LONG_NAME          = 'peroxyacetyl nitrate',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_CO',  &
        LONG_NAME          = 'carbon monoxide',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_ALK4',  &
        LONG_NAME          = '>=C4 alkanes',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_ISOP',  &
        LONG_NAME          = 'isoprene',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_HNO3',  &
        LONG_NAME          = 'nitric acid',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_H2O2',  &
        LONG_NAME          = 'hydrogen peroxide',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_ACET',  &
        LONG_NAME          = 'acetone',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_MEK',  &
        LONG_NAME          = 'methyl ethyl ketone',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_ALD2',  &
        LONG_NAME          = 'acetaldehyde',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_RCHO',  &
        LONG_NAME          = 'lumped aldehyde >=C3',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_MVK',  &
        LONG_NAME          = 'methyl vinyl ketone',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_MACR',  &
        LONG_NAME          = 'methacrolein',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_PMN',  &
        LONG_NAME          = 'peroxymethacryoyl nitrate',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_PPN',  &
        LONG_NAME          = 'lumped peroxyacyl nitrate',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_R4N2',  &
        LONG_NAME          = 'lumped alkyl nitrate',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_PRPE',  &
        LONG_NAME          = '>=C3 alkenes',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_C3H8',  &
        LONG_NAME          = 'propane',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_CH2O',  &
        LONG_NAME          = 'formaldehyde',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_C2H6',  &
        LONG_NAME          = 'ethane',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_N2O5',  &
        LONG_NAME          = 'dinitrogen pentoxide',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_HNO4',  &
        LONG_NAME          = 'pernitric acid',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_MP',  &
        LONG_NAME          = 'methyl hydro peroxide',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_DMS',  &
        LONG_NAME          = 'dimethyl sulfide',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_SO2',  &
        LONG_NAME          = 'sulfur dioxide',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_SO4',  &
        LONG_NAME          = 'sulfate',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_SO4s',  &
        LONG_NAME          = 'sulfate on surface of sea salt aerosol',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_MSA',  &
        LONG_NAME          = 'methyl sulfionic acid',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_NH3',  &
        LONG_NAME          = 'ammonia',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_NH4',  &
        LONG_NAME          = 'ammonium',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_NIT',  &
        LONG_NAME          = 'aerosol nitrate ion',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_NITs',  &
        LONG_NAME          = 'aerosol nitrate ion on surface of sea salt aerosol',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_BCPI',  &
        LONG_NAME          = 'black carbon, hydrophilic',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_OCPI',  &
        LONG_NAME          = 'organic carbon, hydrophilic',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_BCPO',  &
        LONG_NAME          = 'black carbon, hydrophobic',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_OCPO',  &
        LONG_NAME          = 'organic carbon, hydrophobic',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_DST1',  &
        LONG_NAME          = 'dust aerosol, Reff = 0.7 microns',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_DST2',  &
        LONG_NAME          = 'dust aerosol, Reff = 1.4 microns',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_DST3',  &
        LONG_NAME          = 'dust aerosol, Reff = 2.4 microns',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_DST4',  &
        LONG_NAME          = 'dust aerosol, Reff = 4.5 microns',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_SALA',  &
        LONG_NAME          = 'sea salt aerosol, accumulation mode',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_SALC',  &
        LONG_NAME          = 'sea salt aerosol, coarse mode',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_Br2',  &
        LONG_NAME          = 'Br2',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
        FRIENDLYTO         = 'DYNAMICS:TURBULENCE:MOIST',    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_Br',  &
        LONG_NAME          = 'Br',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
        FRIENDLYTO         = 'DYNAMICS:TURBULENCE:MOIST',    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_BrO',  &
        LONG_NAME          = 'BrO',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
        FRIENDLYTO         = 'DYNAMICS:TURBULENCE:MOIST',    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_HOBr',  &
        LONG_NAME          = 'HOBr',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_HBr',  &
        LONG_NAME          = 'HBr',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_BrNO2',  &
        LONG_NAME          = 'BrNO2',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_BrNO3',  &
        LONG_NAME          = 'BrNO3',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_CHBr3',  &
        LONG_NAME          = 'CHBr3',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_CH2Br2',  &
        LONG_NAME          = 'CH2Br2',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_CH3Br',  &
        LONG_NAME          = 'CH3Br',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_MPN',  &
        LONG_NAME          = 'MPN',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_ISOPN',  &
        LONG_NAME          = 'ISOPN',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_MOBA',  &
        LONG_NAME          = 'MOBA',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_PROPNN',  &
        LONG_NAME          = 'PROPNN',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_HAC',  &
        LONG_NAME          = 'HAC',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_GLYC',  &
        LONG_NAME          = 'GLYC',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_MMN',  &
        LONG_NAME          = 'MMN',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_RIP',  &
        LONG_NAME          = 'RIP',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_IEPOX',  &
        LONG_NAME          = 'IEPOX',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_MAP',  &
        LONG_NAME          = 'MAP',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_NO2',  &
        LONG_NAME          = 'NO2',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_NO3',  &
        LONG_NAME          = 'NO3',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'TRC_HNO2',  &
        LONG_NAME          = 'HNO2',  &
        UNITS              = 'mol/mol', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'A3O2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'ACET',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'ACTA',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'ALD2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'ALK4',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'ATO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'B3O2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'Br',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'Br2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'BrNO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'BrNO3',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'BrO',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'C2H6',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'C3H8',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'CH2O',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'CH2Br2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'CH3Br',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'CH4',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'CHBr3',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'CO',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DMS',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYBr2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYBrNO3',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYCH2O',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYH2O2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYHBr',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYHNO3',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYHOBr',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYN2O5',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYNO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYO3',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYPAN',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYPMN',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYPPN',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYR4N2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYMVK',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'DRYMACR',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'EMISSION',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'EOH',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'ETO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'ETP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'GCO3',  &
        LONG_NAME          = 'GCO3',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
        FRIENDLYTO         = trim(COMP_NAME),    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'GLYC',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'GLYX',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'GP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'H',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'H2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'H2O',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'H2O2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'HAC',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'HBr',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'HOBr',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'HCOOH',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'HNO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'HNO3',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'HNO4',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'HO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'IALD',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'IAO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'IAP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'INO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'INPN',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'ISN1',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'ISNP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'ISOP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'KO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'M',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MACR',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MAN2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MAO3',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MAOP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MAP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MCO3',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MEK',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MGLY',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MOH',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MRO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MRP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MSA',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'MVK',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'N2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'N2O5',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'NH2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'NH3',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'NO',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'NO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'NO3',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'O',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'O2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'O3',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'OH',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'PAN',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'PMN',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'PO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'PP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'PPN',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'PRN1',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'PRPE',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'PRPN',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'R4N1',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'R4N2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'R4O2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'R4P',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'RA3P',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'RB3P',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'RCHO',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'RCO3',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'RCOOH',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'RIO1',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'RIO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'RIP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'ROH',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'RP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'SO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'SO4',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'VRO2',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)


     call MAPL_AddInternalSpec(GC, &
        SHORT_NAME         = 'VRP',  &
        LONG_NAME          = '',  &
        UNITS              = 'cm-3', &
        DIMS               = MAPL_DimsHorzVert,    &
        VLOCATION          = MAPL_VLocationCenter,    &
                                                       RC=STATUS  )
     VERIFY_(STATUS)

