#!/bin/csh -f

#######################################################################################
# This script is the driver for QUICKPLOT plots in PORTRAIT mode.
# To produce a list of PORTRAIT plots, simply issue the following 3 commands:
#    (1)  portrait.script -v -list -source $SOURCE > & dummy
#    (2)  grep "plot ==" dummy | tee portrait.list
#    (3)  /bin/rm dummy
# where $SOURCE is an OPTIONAL valid SOURCE directory containing a HISTORY.rc
#######################################################################################


set plots = "residual"
set MAKE_LIST = FALSE

setenv ORIENTATION PORTRAIT
if ( ! $?LONSENV ) then
  setenv LONSENV "0 360"
endif
if ( ! $?LATSENV ) then
  setenv LATSENV "-90 90"
endif

# Set Defaults
# ------------
set    batch = " "
set    debug = "no_debug"
set    expid = '$EXPID'
set   source = '$SOURCE'
set     plot = 'plot'
set   output = '$OUTPUT'
set geosutil = '$GEOSUTIL'
set  seasons = '$SEASON'
set    grads = "grads"


if(! $?STD_DEV ) then
                                setenv STD_DEV FALSE
                                setenv DO_STD  FALSE
else if( ${STD_DEV} == 'true' ) setenv DO_STD  TRUE
endif

if(! $?TAYLOR ) then
   set TAYLOR = FALSE
else
   set TAYLOR = `echo $TAYLOR | tr "[:lower:]" "[:upper:]"`
endif

if(! $?CMPEXP      ) setenv CMPEXP      NULL
if(! $?CMPEXP_ONLY ) setenv CMPEXP_ONLY NULL

@ nmax = $#argv

# Parse command line
# ------------------
@       n  = 1
while( $n <= $nmax )

       if( "$argv[$n]" == "-list" ) then
               set MAKE_LIST = TRUE
       endif

       if( "$argv[$n]" == "-v" ) then
               set echo
       endif

       if( "$argv[$n]" == "-expid" ) then
                    @ n = $n + 1
             set expid  = $argv[$n]
       endif
       if( "$argv[$n]" == "-source" ) then
                    @ n = $n + 1
           set source   = $argv[$n]
       endif
       if( "$argv[$n]" == "-plot"   ) then
                    @ n = $n + 1
             set plot   = $argv[$n]
       endif
       if( "$argv[$n]" == "-output" ) then
                    @ n = $n + 1
             set output = $argv[$n]
       endif
       if( "$argv[$n]" == "-geosutil" ) then
                    @ n = $n + 1
             set geosutil = $argv[$n]
       endif
       if( "$argv[$n]" == "-debug"   ) then
             set debug = "debug"
       endif
       if( "$argv[$n]" == "-zlog"   ) then
                    @ n = $n + 1
             set zlog  = $argv[$n]
       endif
       if( "$argv[$n]" == "-grads"   ) then
                    @ n = $n + 1
             set grads = $argv[$n]
       endif
       if( "$argv[$n]" == "-batch"   ) then
             set batch = "-b"
       endif
       if( "$argv[$n]" == "-season"  ) then
                    @ n = $n + 1
                                      set seasons = ""
                                      set next   = $argv[$n]
                                      set bit    = `echo $next | cut -c1-1`
                                      while( "$bit" != "-" )
                                         set seasons = `echo $seasons $next`
                                          @   n  = $n + 1
                                         if( $n <= $nmax ) then
                                             set next = $argv[$n]
                                             set bit  = `echo $next | cut -c1-1`
                                         else
                                             set bit  = "-"
                                         endif
                                      end
                                             @ n = $n - 1
       endif
     @ n = $n + 1
end

if( $MAKE_LIST == FALSE ) then
    echo "Portrait Script"
    echo "---------------"
    echo "   expid: $expid"
    echo "  source: $source"
    echo "    plot: $plot"
    echo "  output: $output"
    echo "geosutil: $geosutil"
    echo "   debug: $debug"
    echo "  season: $seasons"
    echo "  TAYLOR: $TAYLOR"
    echo " STD_DEV: $STD_DEV"
endif

if( -e $source/.HOMDIR ) then
    set homdir = `cat $source/.HOMDIR`
else
    set homdir = $source
endif

set  plot_type = `echo $plot | cut -c2-5`
if( $plot_type == 'quad' ) then
    setenv PLOT_QUAD true
else
    setenv PLOT_QUAD false
endif

#######################################################################################
#                               Create LIST of Plots
#######################################################################################

     set plotname = ${ORIENTATION}
     @ n = 1

#######################################################################################

# Taylor Plots
# ------------
if( $MAKE_LIST == TRUE | ( $TAYLOR == "TRUE" & $CMPEXP_ONLY == "FALSE" ) ) then
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_olr                $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_cloud              $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_lwp                $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_tpw                $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_tskin              $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_uflux              $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_eflux              $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_hflux              $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog U   DYN   850 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog V   DYN   850 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog T   DYN   850 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog Q   MOIST 850 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog U   DYN   500 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog V   DYN   500 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog T   DYN   500 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog Q   MOIST 500 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog U   DYN   200 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog V   DYN   200 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog T   DYN   200 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog Q   MOIST 200 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog ZLE DYN   300 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog ZLE DYN   500 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/taylor/taylor_prog SLP DYN  1000 $expid $output $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
endif


# Prognostic Zonal Mean Comparisons
# ---------------------------------
     set EXPORTS = `echo U   V   T   Q     RH2   ZLE OMEGA O3`
     set GCS     = `echo DYN DYN DYN MOIST MOIST DYN DYN   CHEMISTRY`
     @ k = 0
     foreach EXPORT ($EXPORTS)
       @ k = $k + 1
       set GC = $GCS[$k]
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/zcmp/progz $EXPORT $GC $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end


# Prognostic Horizontal Mean Dynamics Comparisons
# -----------------------------------------------
     if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/hcmp/hcmp2 SLP DYN 1000 $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     set EXPORTS = `echo U V T ZLE HE OMEGA CHI PSI`
     set LEVS    = '1000 925 850 700 600 500 400 300 250 200 150 100 70 50 30'
     foreach EXPORT ($EXPORTS)
     foreach LEV    ($LEVS)
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/hcmp/hcmp2 $EXPORT DYN $LEV $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end

# Prognostic Horizontal Mean Moist Comparisons
# --------------------------------------------
     set EXPORTS = `echo Q RH2`
     set LEVS    = '1000 925 850 700 600 500 400 300 250 200 150 100 70 50 30'
     foreach EXPORT ($EXPORTS)
     foreach LEV    ($LEVS)
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/hcmp/hcmp2 $EXPORT MOIST $LEV $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end

# Prognostic Horizontal Mean Ozone Comparisons
# --------------------------------------------
     set EXPORTS = `echo O3`
     set LEVS    = '70 50 40 30 10 7 5 4 3 1 .7 .5 .4 .3 .1'
     foreach EXPORT ($EXPORTS)
     foreach LEV    ($LEVS)
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/hcmp/hcmp2 $EXPORT CHEMISTRY $LEV $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end

# Prognostic Horizontal Dynamics Variance Comparisons
# ---------------------------------------------------
     set VARS = `echo U_U V_V T_T ZLE_ZLE OMEGA_OMEGA KE_KE`
     set LEVS = '850 500 200 20'
     foreach VAR ($VARS)
     foreach LEV ($LEVS)
       set EXPORT = `echo $VAR | cut -d_ -f1`
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/quad/hquad -EXPID $expid -EXPORT1 ${EXPORT}:DYN -EXPORT2 ${EXPORT}:DYN -LEV $LEV -SEASON $seasons  -OUTPUT $output -DEBUG $debug" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end

# Prognostic Horizontal Moist Variance Comparisons
# ------------------------------------------------
     set VARS = `echo Q_Q`
     set LEVS = '850 500 200 20'
     foreach VAR ($VARS)
     foreach LEV ($LEVS)
       set EXPORT = `echo $VAR | cut -d_ -f1`
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/quad/hquad -EXPID $expid -EXPORT1 ${EXPORT}:MOIST -EXPORT2 ${EXPORT}:MOIST -LEV $LEV -SEASON $seasons  -OUTPUT $output -DEBUG $debug" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end

# Prognostic Horizontal Moist CoVariance Comparisons
# --------------------------------------------------
     set VARS = `echo U_V V_T V_Q OMEGA_T OMEGA_Q`
     set LEVS = '850 500 200 20'
     foreach VAR ($VARS)
     foreach LEV ($LEVS)
       set EXPORT1 = `echo $VAR | cut -d_ -f1`
       set EXPORT2 = `echo $VAR | cut -d_ -f2`
       set GRDCMP1 = DYN
       set GRDCMP2 = DYN
       if($EXPORT2 == Q ) set GRDCMP2 = MOIST
       if( $plot == $plotname.$n ) $grads $batch -p -c "run $GEOSUTIL/plots/quad/hquad -EXPID $expid -EXPORT1 ${EXPORT1}:${GRDCMP1} -EXPORT2 ${EXPORT2}:${GRDCMP2} -LEV $LEV -SEASON $seasons -OUTPUT $output -DEBUG $debug" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
     end
     end


# Residual Circulation
# --------------------
if( $plot == residual ) then
                             $GEOSUTIL/plots/res/makeres      $source
    $grads $batch -p -c "run $GEOSUTIL/plots/res/res   $expid $output $debug $seasons "
endif


# Surface/2-D
# -----------
    set EXPORTS = "CN_PRCP:MOIST LS_PRCP:MOIST AN_PRCP:MOIST"
    set     OBS = "TPREC:MOIST"
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT $EXPORTS -OBS $OBS -NAME precip  -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 86400                    -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT $EXPORTS -OBS $OBS -NAME precip  -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 86400 -PREFIX LAND -LAND -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run  $GEOSUTIL/plots/precip/precip $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run  $GEOSUTIL/plots/olr/olr       $expid $output $debug $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   SH:SURFACE    -NAME hflux   -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 1 -PREFIX LAND  -LAND  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   SH:SURFACE    -NAME hflux   -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 1               -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   LHFX:SURFACE  -NAME eflux   -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 1 -PREFIX LAND  -LAND  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   LHFX:SURFACE  -NAME eflux   -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 1               -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LWP:MOIST CCWP:MOIST -OBS LWP:MOIST -NAME lwp  -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 1000 -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TQV:AGCM   -NAME tpw  -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 0.1 -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT  VENT:SURFACE   -NAME speed   -EXPID $expid -OUTPUT $output -DEBUG $debug            -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT     TS:SURFACE  -NAME sst     -EXPID $expid -OUTPUT $output -DEBUG $debug            -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT     TS:SURFACE  -NAME tskin   -EXPID $expid -OUTPUT $output -DEBUG $debug            -LAND  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   TAUX:SURFACE  -NAME taux    -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 100 -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   TAUY:SURFACE  -NAME tauy    -EXPID $expid -OUTPUT $output -DEBUG $debug -SCALE 100 -OCEAN -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT ALBEDO:SOLAR    -NAME albedo  -EXPID $expid -OUTPUT $output -DEBUG $debug                   -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT TBISCCP:SATSIM                                                                       -NAME tb       -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT RADSRF:RADIATION LHFX:SURFACE SH:SURFACE -OBS QNET:RADIATION                         -NAME NETHEATG -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT EVAP:SURFACE CN_PRCP:MOIST LS_PRCP:MOIST AN_PRCP:MOIST -OBS EVAP:SURFACE TPREC:MOIST -NAME emp      -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Surface/2-D: Clouds
# -------------------
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDLO:SOLAR   -NAME cldlo   -EXPID $expid -OUTPUT $output -DEBUG $debug                  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDMD:SOLAR   -NAME cldmd   -EXPID $expid -OUTPUT $output -DEBUG $debug                  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDHI:SOLAR   -NAME cldhi   -EXPID $expid -OUTPUT $output -DEBUG $debug                  -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDTT:SOLAR   -NAME cldtt   -EXPID $expid -OUTPUT $output -DEBUG $debug        -RC SRB   -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDTT:SOLAR   -NAME cldtt   -EXPID $expid -OUTPUT $output -DEBUG $debug        -RC ISCCP -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT CLDTT:SOLAR   -NAME cldtt   -EXPID $expid -OUTPUT $output -DEBUG $debug -OCEAN -RC COADS -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1



# Radiation: Shortwave
# --------------------
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME radswt   -EXPID $expid -EXPORT SLRTP:SOLAR              -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgnet   -EXPID $expid -EXPORT  RSRS:SOLAR              -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgnetc  -EXPID $expid -EXPORT  RSCS:SOLAR -OBS SLRSFC:SOLAR ALBEDO:SOLAR -OUTPUT $output -DEBUG $debug -SEASON $seasons "                       ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgnetcf -EXPID $expid -EXPORT  RSCS:SOLAR RSRS:SOLAR -OBS SLRSFC:SOLAR ALBEDO:SOLAR RSRS:SOLAR -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgdwn   -EXPID $expid -EXPORT SLRSF:SOLAR              -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgdwnc  -EXPID $expid -EXPORT SLRSFC:SOLAR             -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgdwncf -EXPID $expid -EXPORT SLRSFC:SOLAR SLRSF:SOLAR -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME osr      -EXPID $expid -EXPORT RSR:SOLAR                -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME osrc     -EXPID $expid -EXPORT RSC:SOLAR                -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME osrcf    -EXPID $expid -EXPORT RSC:SOLAR RSR:SOLAR      -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgup    -EXPID $expid -EXPORT SLRSF:SOLAR  RSRS:SOLAR  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgupc   -EXPID $expid -EXPORT SLRSFC:SOLAR RSCS:SOLAR -OBS ALBEDO:SOLAR SLRSFC:SOLAR -OUTPUT $output -DEBUG $debug -SEASON $seasons "                                               ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME swgupcf  -EXPID $expid -EXPORT SLRSFC:SOLAR RSCS:SOLAR SLRSF:SOLAR RSRS:SOLAR -OBS ALBEDO:SOLAR SLRSFC:SOLAR SLRSF:SOLAR RSRS:SOLAR -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
 

# Radiation: Longwave
# -------------------
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT OLC:IRRAD OLR:IRRAD OSRCLR:SOLAR OSR:SOLAR -NAME toacf -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   OLR:IRRAD   -NAME olr     -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   OLC:IRRAD   -NAME olrc    -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT OLCC5:IRRAD   -NAME olrcc5  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT OLC:IRRAD  OLR:IRRAD                      -NAME olrcf   -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   LWS:IRRAD EMIS:SURFACE -OBS  SFCDWN:IRRAD -NAME lwgdwn    -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT   LCS:IRRAD EMIS:SURFACE -OBS SFCDWNC:IRRAD -NAME lwgdwnc   -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
#  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LCSC5:IRRAD EMIS:SURFACE -OBS SFCDWNC:IRRAD -NAME lwgdwncc5 -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LWS:IRRAD LCS:IRRAD EMIS:SURFACE -OBS SFCDWN:IRRAD SFCDWNC:IRRAD -NAME lwgdwncf  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons "             ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT SFCEM:IRRAD LWS:IRRAD -OBS SFCUP:IRRAD SFCDWN:IRRAD -NAME lwgnet    -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons "                          ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT SFCEM:IRRAD LCS:IRRAD -OBS SFCUPC:IRRAD SFCDWNC:IRRAD -NAME lwgnetc   -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons "                        ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LWS:IRRAD LCS:IRRAD -OBS SFCUPC:IRRAD SFCDWNC:IRRAD SFCUP:IRRAD SFCDWN:IRRAD -NAME lwgnetcf  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT SFCEM:IRRAD EMIS:SURFACE LWS:IRRAD -OBS SFCUP:IRRAD -NAME lwgup   -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons "            ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT SFCEM:IRRAD EMIS:SURFACE LCS:IRRAD -OBS SFCUPC:IRRAD -NAME lwgupc  -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons "           ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
   if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -EXPORT LWS:IRRAD LCS:IRRAD EMIS:SURFACE -OBS SFCUP:IRRAD SFCUPC:IRRAD -NAME lwgupcf -EXPID $expid -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1


# Radiation: Net
# --------------
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME radnetg  -EXPID $expid -EXPORT RADSRF:RADIATION       -OBS RSRS:SOLAR SFCUP:IRRAD SFCDWN:IRRAD -OUTPUT $output -DEBUG $debug -SEASON $seasons "                  ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME radnetgc -EXPID $expid -EXPORT RSCS:SOLAR FLNSC:IRRAD -OBS SLRSFC:SOLAR ALBEDO:SOLAR SFCUPC:IRRAD SFCDWNC:IRRAD -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME nettoa   -EXPID $expid -EXPORT RSR:SOLAR OLR:IRRAD    -OBS RSR:SOLAR OLR:IRRAD -OUTPUT $output -DEBUG $debug -SEASON $seasons "                                  ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -NAME nettoac  -EXPID $expid -EXPORT RSC:SOLAR OLC:IRRAD    -OBS RSC:SOLAR OLC:IRRAD -OUTPUT $output -DEBUG $debug -SEASON $seasons "                                  ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1


# Aerosols:
# ---------
  setenv LONSENV "-180 180"
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TTAUDU   -EXPID $expid   -EXPORT    TTAUDU:SOLAR   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TTAUSS   -EXPID $expid   -EXPORT    TTAUSS:SOLAR   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TTAUSO   -EXPID $expid   -EXPORT    TTAUSO:SOLAR   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TTAUBC   -EXPID $expid   -EXPORT    TTAUBC:SOLAR   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TTAUOC   -EXPID $expid   -EXPORT    TTAUOC:SOLAR   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TDUST    -EXPID $expid   -EXPORT     TDUST:SOLAR   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TSALT    -EXPID $expid   -EXPORT     TSALT:SOLAR   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TSO4     -EXPID $expid   -EXPORT      TSO4:SOLAR   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TBC      -EXPID $expid   -EXPORT       TBC:SOLAR   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TOC      -EXPID $expid   -EXPORT       TOC:SOLAR   -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TOTEXTTAU -EXPID $expid  -EXPORT TOTEXTTAU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TOTSCATAU -EXPID $expid  -EXPORT TOTSCATAU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME TOTANGSTR -EXPID $expid  -EXPORT TOTANGSTR:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUEM001   -EXPID $expid  -EXPORT   DUEM001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUEM002   -EXPID $expid  -EXPORT   DUEM002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUEM003   -EXPID $expid  -EXPORT   DUEM003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUEM004   -EXPID $expid  -EXPORT   DUEM004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUEM005   -EXPID $expid  -EXPORT   DUEM005:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSD001   -EXPID $expid  -EXPORT   DUSD001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSD002   -EXPID $expid  -EXPORT   DUSD002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSD003   -EXPID $expid  -EXPORT   DUSD003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSD004   -EXPID $expid  -EXPORT   DUSD004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSD005   -EXPID $expid  -EXPORT   DUSD005:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUPD001   -EXPID $expid  -EXPORT   DUPD001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUPD002   -EXPID $expid  -EXPORT   DUPD002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUPD003   -EXPID $expid  -EXPORT   DUPD003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUPD004   -EXPID $expid  -EXPORT   DUPD004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUPD005   -EXPID $expid  -EXPORT   DUPD005:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUWT001   -EXPID $expid  -EXPORT   DUWT001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUWT002   -EXPID $expid  -EXPORT   DUWT002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUWT003   -EXPID $expid  -EXPORT   DUWT003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUWT004   -EXPID $expid  -EXPORT   DUWT004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUWT005   -EXPID $expid  -EXPORT   DUWT005:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSV001   -EXPID $expid  -EXPORT   DUSV001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSV002   -EXPID $expid  -EXPORT   DUSV002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSV003   -EXPID $expid  -EXPORT   DUSV003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSV004   -EXPID $expid  -EXPORT   DUSV004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSV005   -EXPID $expid  -EXPORT   DUSV005:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUDP001   -EXPID $expid  -EXPORT   DUDP001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUDP002   -EXPID $expid  -EXPORT   DUDP002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUDP003   -EXPID $expid  -EXPORT   DUDP003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUDP004   -EXPID $expid  -EXPORT   DUDP004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUDP005   -EXPID $expid  -EXPORT   DUDP005:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSMASS   -EXPID $expid  -EXPORT   DUSMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUCMASS   -EXPID $expid  -EXPORT   DUCMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSMASS25 -EXPID $expid  -EXPORT DUSMASS25:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUCMASS25 -EXPID $expid  -EXPORT DUCMASS25:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUEXTT25  -EXPID $expid  -EXPORT  DUEXTT25:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSCAT25  -EXPID $expid  -EXPORT  DUSCAT25:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUEXTTAU  -EXPID $expid  -EXPORT  DUEXTTAU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSCATAU  -EXPID $expid  -EXPORT  DUSCATAU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUANGSTR  -EXPID $expid  -EXPORT  DUANGSTR:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUEXTTFM  -EXPID $expid  -EXPORT  DUEXTTFM:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUSCATFM  -EXPID $expid  -EXPORT  DUSCATFM:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUFLUXU   -EXPID $expid  -EXPORT   DUFLUXU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DUFLUXV   -EXPID $expid  -EXPORT   DUFLUXV:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSEM001   -EXPID $expid  -EXPORT   SSEM001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSEM002   -EXPID $expid  -EXPORT   SSEM002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSEM003   -EXPID $expid  -EXPORT   SSEM003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSEM004   -EXPID $expid  -EXPORT   SSEM004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSEM005   -EXPID $expid  -EXPORT   SSEM005:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSD001   -EXPID $expid  -EXPORT   SSSD001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSD002   -EXPID $expid  -EXPORT   SSSD002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSD003   -EXPID $expid  -EXPORT   SSSD003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSD004   -EXPID $expid  -EXPORT   SSSD004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSD005   -EXPID $expid  -EXPORT   SSSD005:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSDP001   -EXPID $expid  -EXPORT   SSDP001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSDP002   -EXPID $expid  -EXPORT   SSDP002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSDP003   -EXPID $expid  -EXPORT   SSDP003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSDP004   -EXPID $expid  -EXPORT   SSDP004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSDP005   -EXPID $expid  -EXPORT   SSDP005:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSWT001   -EXPID $expid  -EXPORT   SSWT001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSWT002   -EXPID $expid  -EXPORT   SSWT002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSWT003   -EXPID $expid  -EXPORT   SSWT003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSWT004   -EXPID $expid  -EXPORT   SSWT004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSWT005   -EXPID $expid  -EXPORT   SSWT005:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSV001   -EXPID $expid  -EXPORT   SSSV001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSV002   -EXPID $expid  -EXPORT   SSSV002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSV003   -EXPID $expid  -EXPORT   SSSV003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSV004   -EXPID $expid  -EXPORT   SSSV004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSV005   -EXPID $expid  -EXPORT   SSSV005:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSMASS   -EXPID $expid  -EXPORT   SSSMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSCMASS   -EXPID $expid  -EXPORT   SSCMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSEXTTAU  -EXPID $expid  -EXPORT  SSEXTTAU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSCATAU  -EXPID $expid  -EXPORT  SSSCATAU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSANGSTR  -EXPID $expid  -EXPORT  SSANGSTR:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSEXTTFM  -EXPID $expid  -EXPORT  SSEXTTFM:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSCATFM  -EXPID $expid  -EXPORT  SSSCATFM:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSMASS25 -EXPID $expid  -EXPORT SSSMASS25:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSCMASS25 -EXPID $expid  -EXPORT SSCMASS25:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSEXTT25  -EXPID $expid  -EXPORT  SSEXTT25:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSSCAT25  -EXPID $expid  -EXPORT  SSSCAT25:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSFLUXU   -EXPID $expid  -EXPORT   SSFLUXU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SSFLUXV   -EXPID $expid  -EXPORT   SSFLUXV:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUEM001   -EXPID $expid  -EXPORT   SUEM001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUEM002   -EXPID $expid  -EXPORT   SUEM002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUEM003   -EXPID $expid  -EXPORT   SUEM003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUEM004   -EXPID $expid  -EXPORT   SUEM004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUDP001   -EXPID $expid  -EXPORT   SUDP001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUDP002   -EXPID $expid  -EXPORT   SUDP002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUDP003   -EXPID $expid  -EXPORT   SUDP003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUDP004   -EXPID $expid  -EXPORT   SUDP004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUWT001   -EXPID $expid  -EXPORT   SUWT001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUWT002   -EXPID $expid  -EXPORT   SUWT002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUWT003   -EXPID $expid  -EXPORT   SUWT003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUWT004   -EXPID $expid  -EXPORT   SUWT004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUSV001   -EXPID $expid  -EXPORT   SUSV001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUSV002   -EXPID $expid  -EXPORT   SUSV002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUSV003   -EXPID $expid  -EXPORT   SUSV003:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUSV004   -EXPID $expid  -EXPORT   SUSV004:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SO2SMASS  -EXPID $expid  -EXPORT  SO2SMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SO2CMASS  -EXPID $expid  -EXPORT  SO2CMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SO4SMASS  -EXPID $expid  -EXPORT  SO4SMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SO4CMASS  -EXPID $expid  -EXPORT  SO4CMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DMSSMASS  -EXPID $expid  -EXPORT  DMSSMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME DMSCMASS  -EXPID $expid  -EXPORT  DMSCMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUPMSA    -EXPID $expid  -EXPORT    SUPMSA:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUPSO2    -EXPID $expid  -EXPORT    SUPSO2:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUPSO4G   -EXPID $expid  -EXPORT   SUPSO4G:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUPSO4AQ  -EXPID $expid  -EXPORT  SUPSO4AQ:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUPSO4WT  -EXPID $expid  -EXPORT  SUPSO4WT:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUEXTTAU  -EXPID $expid  -EXPORT  SUEXTTAU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUSCATAU  -EXPID $expid  -EXPORT  SUSCATAU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUANGSTR  -EXPID $expid  -EXPORT  SUANGSTR:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SO4EMAN   -EXPID $expid  -EXPORT   SO4EMAN:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SO2EMAN   -EXPID $expid  -EXPORT   SO2EMAN:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SO2EMBB   -EXPID $expid  -EXPORT   SO2EMBB:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SO2EMVN   -EXPID $expid  -EXPORT   SO2EMVN:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SO2EMVE   -EXPID $expid  -EXPORT   SO2EMVE:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUFLUXU   -EXPID $expid  -EXPORT   SUFLUXU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME SUFLUXV   -EXPID $expid  -EXPORT   SUFLUXV:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCEM001   -EXPID $expid  -EXPORT   BCEM001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCEM002   -EXPID $expid  -EXPORT   BCEM002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCDP001   -EXPID $expid  -EXPORT   BCDP001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCDP002   -EXPID $expid  -EXPORT   BCDP002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCWT001   -EXPID $expid  -EXPORT   BCWT001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCWT002   -EXPID $expid  -EXPORT   BCWT002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCSV001   -EXPID $expid  -EXPORT   BCSV001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCSV002   -EXPID $expid  -EXPORT   BCSV002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCSMASS   -EXPID $expid  -EXPORT   BCSMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCCMASS   -EXPID $expid  -EXPORT   BCCMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCEXTTAU  -EXPID $expid  -EXPORT  BCEXTTAU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCSCATAU  -EXPID $expid  -EXPORT  BSCATTAU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCANGSTR  -EXPID $expid  -EXPORT  BCANGSTR:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCHYPHIL  -EXPID $expid  -EXPORT  BCHYPHIL:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCEMBB    -EXPID $expid  -EXPORT    BCEMBB:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCEMBF    -EXPID $expid  -EXPORT    BCEMBF:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCEMAN    -EXPID $expid  -EXPORT    BCEMAN:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCFLUXU   -EXPID $expid  -EXPORT   BCFLUXU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME BCFLUXV   -EXPID $expid  -EXPORT   BCFLUXV:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCEM001   -EXPID $expid  -EXPORT   OCEM001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCEM002   -EXPID $expid  -EXPORT   OCEM002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCDP001   -EXPID $expid  -EXPORT   OCDP001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCDP002   -EXPID $expid  -EXPORT   OCDP002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCWT001   -EXPID $expid  -EXPORT   OCWT001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCWT002   -EXPID $expid  -EXPORT   OCWT002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCSV001   -EXPID $expid  -EXPORT   OCSV001:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCSV002   -EXPID $expid  -EXPORT   OCSV002:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCSMASS   -EXPID $expid  -EXPORT   OCSMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCCMASS   -EXPID $expid  -EXPORT   OCCMASS:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCEXTTAU  -EXPID $expid  -EXPORT  OCEXTTAU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCSCATAU  -EXPID $expid  -EXPORT  OSCATTAU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCANGSTR  -EXPID $expid  -EXPORT  OCANGSTR:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCHYPHIL  -EXPID $expid  -EXPORT  OCHYPHIL:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCEMBB    -EXPID $expid  -EXPORT    OCEMBB:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCEMBF    -EXPID $expid  -EXPORT    OCEMBF:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCEMAN    -EXPID $expid  -EXPORT    OCEMAN:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCFLUXU   -EXPID $expid  -EXPORT   OCFLUXU:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  if( $plot == $plotname.$n ) $grads $batch -p -c "run genplot -DIR aerosol -NAME OCFLUXV   -EXPID $expid  -EXPORT   OCFLUXV:GOCART  -MATH LOG  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
  setenv LONSENV "0 360"


# --------------

# Experiment Comparison Plots
# ---------------------------
if( $MAKE_LIST == TRUE | "$CMPEXP" != "NULL" ) then

# Surface/2-D Diagnostics
# -----------------------
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT TROPP_BLENDED:AGCM        -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT         TROPQ:AGCM        -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT         TROPT:AGCM        -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT            TS:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT            Z0:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           Z0H:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT          EMIS:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT          VENT:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT            US:DYN         -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT            VS:DYN         -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT        SNOMAS:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           LAI:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           GRN:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT          EVAP:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           T2M:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           Q2M:SURFACE     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           THAT:SURFACE    -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           QHAT:SURFACE    -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           WET1:SURFACE    -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           CLDLO:SOLAR     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           CLDMD:SOLAR     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           CLDHI:SOLAR     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           CLDTT:SOLAR     -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           ZPBL:TURBULENCE -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT           DMDT:PHYSICS    -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Dynamics Diagnostics
# --------------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDTDYN:DYN    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDTDYN:DYN    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDTDYN:DYN    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10 0.1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQVDTDYN:DYN    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"     ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    OMEGA:DYN    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"     ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DMDTDYN:DYN  DMDTANA:DYN  DMDT:PHYSICS  -NAME DMDTDYNANAPHY  -LEVEL 0" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DMDTDYN:DYN  DMDTANA:DYN                -NAME DMDTDYNANA     -LEVEL 0" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DMDTDYN:DYN                                                  -LEVEL 0" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      set LEVS = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300 250 200 150 100'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DUDTDYN:DYN -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DVDTDYN:DYN -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDTDYN:DYN -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQVDTDYN:DYN -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    OMEGA:DYN -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

# Moist Processes Diagnostics
# ---------------------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT FCLD:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DUDT:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DVDT:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT TIM:PHYSICS     -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQDT:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QLTOT:AGCM      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT QITOT:AGCM      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RL:MOIST        -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RI:MOIST        -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT FCLD:MOIST      -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT CNV_MF0:MOIST   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT CNV_MFD:MOIST   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT CNV_MFC:MOIST   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT REV_CN:MOIST    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT REV_AN:MOIST    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT REV_LS:MOIST    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RSU_CN:MOIST    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RSU_AN:MOIST    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RSU_LS:MOIST    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      set LEVS = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300 250 200 150 100'

      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DUDT:MOIST     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DVDT:MOIST     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  TIM:PHYSICS   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQDT:MOIST     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QLTOT:AGCM     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT QITOT:AGCM     -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RL:MOIST       -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RI:MOIST       -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    FCLD:MOIST  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT CNV_MF0:MOIST  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT CNV_MFD:MOIST  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT CNV_MFC:MOIST  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT REV_CN:MOIST   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT REV_AN:MOIST   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT REV_LS:MOIST   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RSU_CN:MOIST   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RSU_AN:MOIST   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RSU_LS:MOIST   -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

# Turbulence Diagnostics
# ----------------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      UIT:PHYSICS    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      VIT:PHYSICS    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      TIT:PHYSICS    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     QVIT:PHYSICS    -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     KM:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     KH:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT   KMLS:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT   KHLS:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  KHSFC:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  KHRAD:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    EKH:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT    EKM:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     RI:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT INTDIS:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT TOPDIS:TURBULENCE   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      set LEVS = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     KM:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     KH:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT   KMLS:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT   KHLS:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  KHSFC:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  KHRAD:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    EKH:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    EKM:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     RI:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT INTDIS:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT TOPDIS:TURBULENCE -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    UIT:PHYSICS    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    VIT:PHYSICS    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT    TIT:PHYSICS    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT   QVIT:PHYSICS    -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

# Gravity Wave Drag Diagnostics
# -----------------------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT:GWD       -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT:GWD       -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT TTMGW:GWD       -SEASON $seasons -OUTPUT $output -DEBUG $debug " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT_BKG:GWD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT_BKG:GWD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDT_BKG:GWD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT_ORO:GWD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT_ORO:GWD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDT_ORO:GWD   -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      set LEVS = '400 300 200 100 50 10 5 2 1 .4 .2 .1 .04 .02'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DUDT:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DVDT:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     TTMGW:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DUDT_BKG:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DVDT_BKG:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDT_BKG:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DUDT_ORO:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DVDT_ORO:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDT_ORO:GWD -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

# Radiation Diagnostics
# ---------------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RADLW:RADIATION -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT RADSW:RADIATION -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      set LEVS = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300 250 200 150 100'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RADLW:RADIATION -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT RADSW:RADIATION -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  OLA:IRRAD    OLC:IRRAD  -NAME OLRCAF    -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  LCS:IRRAD    LAS:IRRAD  -NAME LWGNETCAF -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  RSR:SOLAR  RSRNA:SOLAR  -NAME SWTNETAF  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  RSC:SOLAR  RSCNA:SOLAR  -NAME SWTNETCAF -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT RSRS:SOLAR RSRSNA:SOLAR  -NAME SWGNETAF  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT RSCS:SOLAR RSCSNA:SOLAR  -NAME SWGNETCAF -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

# Analysis Diagnostics
# --------------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT_ANA:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DTDT_ANA:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT_ANA:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10 0.1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT DQVDT_ANA:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"     ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DUDT:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10 0.1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DVDT:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10 0.1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT      DTDT:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10 0.1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT     DQVDT:AGCM  -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"     ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT     DMDTANA:DYN  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT DQVDTANAINT:DYN  -OUTPUT $output -DEBUG $debug -SEASON $seasons " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      set LEVS = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300 250 200 150 100'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DUDT_ANA:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DVDT_ANA:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT  DTDT_ANA:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT DQVDT_ANA:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DUDT:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DVDT:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT      DTDT:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -SEASON $seasons -OUTPUT $output -DEBUG $debug -EXPORT     DQVDT:AGCM  -LEVEL $LEV " ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

# Total Tendencies
# ----------------
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT:MOIST   UIT:PHYSICS DUDT:GWD                                              -NAME DUDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  TIM:PHYSICS  TIT:PHYSICS TTMGW:GWD RADLW:RADIATION RADSW:RADIATION             -NAME DTDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT                                     RADLW:RADIATION RADSW:RADIATION             -NAME DTDTRAD -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT:MOIST   VIT:PHYSICS DVDT:GWD                                              -NAME DVDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10 0.1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DQDT:MOIST  QVIT:PHYSICS                                                       -NAME DQDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"     ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DUDT:MOIST   UIT:PHYSICS DUDT:GWD                                  DUDTDYN:DYN   DUDT_ANA:AGCM:OPT -NAME DUDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  TIM:PHYSICS  TIT:PHYSICS TTMGW:GWD RADLW:RADIATION RADSW:RADIATION DTDTDYN:DYN   DTDT_ANA:AGCM:OPT -NAME DTDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 30:L 10 0.1:L" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DVDT:MOIST   VIT:PHYSICS DVDT:GWD                                  DVDTDYN:DYN   DVDT_ANA:AGCM:OPT -NAME DVDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10 0.1" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT  DQDT:MOIST  QVIT:PHYSICS                                           DQVDTDYN:DYN DQVDT_ANA:AGCM:OPT -NAME DQDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -PTOP 10"     ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      set LEVS = '1000 975 950 925 900 850 800 750 700 650 600 550 500 450 400 350 300 250 200 150 100'
      foreach LEV ($LEVS)
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DUDT:MOIST  UIT:PHYSICS DUDT:GWD                                               -NAME DUDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DVDT:MOIST  VIT:PHYSICS DVDT:GWD                                               -NAME DVDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DQDT:MOIST QVIT:PHYSICS                                                        -NAME DQDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  TIM:PHYSICS  TIT:PHYSICS TTMGW:GWD RADLW:RADIATION RADSW:RADIATION             -NAME DTDTPHY -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT                                     RADLW:RADIATION RADSW:RADIATION             -NAME DTDTRAD -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1

      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DUDT:MOIST  UIT:PHYSICS DUDT:GWD                                   DUDTDYN:DYN  DUDT_ANA:AGCM:OPT -NAME DUDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DVDT:MOIST  VIT:PHYSICS DVDT:GWD                                   DVDTDYN:DYN  DVDT_ANA:AGCM:OPT -NAME DVDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  DQDT:MOIST QVIT:PHYSICS                                           DQVDTDYN:DYN DQVDT_ANA:AGCM:OPT -NAME DQDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      if( $plot == $plotname.$n ) $grads $batch -p -c "run gencmp -EXPID $expid -EXPORT  TIM:PHYSICS  TIT:PHYSICS TTMGW:GWD RADLW:RADIATION RADSW:RADIATION DTDTDYN:DYN  DTDT_ANA:AGCM:OPT -NAME DTDTTOT -SEASON $seasons -OUTPUT $output -DEBUG $debug -LEVEL $LEV" ; set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
      end

# End Experiment Comparison Plots
# -------------------------------
endif

#######################################################################################

set  FOUND = "TRUE"
if( $FOUND == FALSE ) then

#######################################################################################
#  User-Specified 2-D Plots that Match Existing Cases (eg., -type 2 -plots OLR:IRRAD )
#######################################################################################

echo " "
echo "Starting TEST for Pre-Existing plots ..."

set EXPORT = `echo $plot | cut -d: -f1`
set GC     = `echo $plot | cut -d: -f2`
set LEV    = `echo $plot | cut -d: -f3`

echo " "
echo "  PLOT: $plot"
echo "EXPORT: $EXPORT"
echo "    GC: $GC"
echo "   LEV: $LEV"
echo " "

# Find Existing Command to Execute for $plot in the form: EXPORT:GC<:LEV>
# -----------------------------------------------------------------------
# DONE
if( $plot =~ *:* & $FOUND == FALSE ) then
    set numlines = `wc -l $GEOSUTIL/plots/portrait.script | cut -d' ' -f1`
    @ m  = 1
    while( $m <= $numlines )
      set   line  = `awk -v ln=$m '{if (NR==ln) print $0}' $GEOSUTIL/plots/portrait.script`
      if( "$line" == "# DONE") then
          @ m  = $numlines
      endif
          set commands = ''
      if( .$LEV == . ) then
          set commands = `echo $line | grep ${EXPORT}:${GC}`
      else
          if( $LEV != '' & $LEV != 'Z' & $LEV != 'z' ) then 
          set commands = `echo $line | grep ${EXPORT}:${GC} | grep $LEV`
          endif
      endif
      set num = $#commands
        @ n = 2
      set dum = '$grads'
      while( $n <= $num )
         set   command   =  $commands[$n]
         if( "$command" != '$grads' ) set dum = "$dum $command"
         if( "$command" == '$grads' | $n == $num ) then
          /bin/rm -f command.file
          touch      command.file
          echo  \#\!/bin/tcsh -f            >> command.file
          echo "set LEV     = $LEV"         >> command.file
          echo "set grads   = $grads"       >> command.file
          echo "set expid   = $expid"       >> command.file
          echo "set output  = $output"      >> command.file
          echo "set debug   = $debug"       >> command.file
          echo "set batch   = $batch"       >> command.file
          echo 'set seasons = "'$seasons'"' >> command.file
          echo "$dum"                       >> command.file
          chmod +x command.file
          echo " "
          echo "Issuing command.file: ${n}"
          echo "---------------------"
          cat command.file
          echo " "
            ./command.file
          set dum = '$grads'
         endif
      @ n = $n + 1
      end
    @ m = $m + 1
    end
endif

#######################################################################################

endif

#######################################################################################
#               Experiment Comparison Plots that are NOT Pre-Existing
#######################################################################################


set EXPORT0 = `echo $plot | cut -d: -f1`
set GC0     = `echo $plot | cut -d: -f2`
set LEV0    = `echo $plot | cut -d: -f3`

if( $MAKE_LIST == FALSE ) then
echo " "
echo "Starting TEST for NON Pre-Existing Comparison Plots ..."
echo " "
endif

if( $MAKE_LIST == TRUE | "$CMPEXP" != "NULL" ) then

        if( -e $homdir/HISTORY.rc ) then
          set EXPORTS = `$GEOSUTIL/plots/get_exports  $homdir/HISTORY.rc  portrait.script`
          foreach pair ($EXPORTS)
             set EXPORT   = `echo $pair | cut -d: -f1`
             set GC       = `echo $pair | cut -d: -f2`
             set LEV      = ''
             set command  = `grep ${EXPORT}:${GC} $GEOSUTIL/plots/portrait.script`
             set numplots =  $#command

             if( "$numplots" == "0" ) then
                  if( $MAKE_LIST == TRUE ) then
                     if( plot == $plotname.$n ) $grads $batch -p -c "run gencmp(z) -EXPID $expid -EXPORT ${EXPORT}:${GC} -OUTPUT ${output}/misc -DEBUG $debug -SEASON $seasons "
                  endif
                  if( $MAKE_LIST == FALSE ) then
                     if( $plot == $plotname.$n ) then
                         $grads     -b -p -c "run getzdim ${EXPORT} ${GC} $source" &
                         wait
                         set NLEVS = `cat ${EXPORT}:${GC}:NLEVS.txt`
                         /bin/rm       -f ${EXPORT}:${GC}:NLEVS.txt

                         if( $NLEVS == 1 ) then 
                             echo "Issuing genmcp for: $plotname.$n ${EXPORT}:${GC}  NLEVS: $NLEVS"
                             echo "------------------"
                             $grads $batch -p -c "run gencmp  -EXPID $expid -EXPORT ${EXPORT}:${GC} -OUTPUT ${output}/misc -DEBUG $debug -SEASON $seasons "
                         else
                             echo "Issuing genmcpz for: $plotname.$n ${EXPORT}:${GC}  NLEVS: $NLEVS"
                             echo "-------------------"
                             $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT ${EXPORT}:${GC} -OUTPUT ${output}/misc -DEBUG $debug -SEASON $seasons "
                         endif
                     endif
                     if( .$EXPORT == .$EXPORT0 & .$GC0 == .$GC ) then
                         $grads     -b -p -c "run getzdim ${EXPORT} ${GC} $source" &
                         wait
                         set NLEVS = `cat ${EXPORT}:${GC}:NLEVS.txt`
                         /bin/rm       -f ${EXPORT}:${GC}:NLEVS.txt

                         if( $NLEVS == 1 ) then 
                             echo "Issuing genmcp for: $plotname.$n ${EXPORT}:${GC}  NLEVS: $NLEVS"
                             echo "------------------"
                             $grads $batch -p -c "run gencmp  -EXPID $expid -EXPORT ${EXPORT}:${GC} -OUTPUT ${output}/misc -DEBUG $debug -SEASON $seasons "
                             $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT ${EXPORT}:${GC} -OUTPUT ${output}/misc -DEBUG $debug -SEASON $seasons "
                         else
                             echo "Issuing genmcpz for: $plotname.$n ${EXPORT}:${GC}  NLEVS: $NLEVS"
                             echo "-------------------"
                             $grads $batch -p -c "run gencmpz -EXPID $expid -EXPORT ${EXPORT}:${GC} -OUTPUT ${output}/misc -DEBUG $debug -SEASON $seasons "
                         endif
                     endif
                  endif
                 set plots = `echo $plots $plotname.$n` ; @ n = $n + 1
             endif
          end
        endif

endif

#######################################################################################

if( $MAKE_LIST == TRUE ) echo $plots

exit
