#!/bin/csh

set name   = $1
set pltdir = $2

set file = $pltdir/$name

# Create Postscript from Grads
# ----------------------------
        if( -e $file.out ) then
                gxps -c -i $file.out -o $file.ps
        endif

# Create GIF from Postscript
# --------------------------
        if( -e $file.ps ) then
                convert -seed 1 -density 90x90 $file.ps $file.gif
        endif

# Remove Intermediate Files
# -------------------------
        if( -e $file.gif ) then
               /bin/rm   $file.out $file.ps
               chmod 644 $file.gif
        endif
