# $Id: makefile,v 1.1.5.1 2013-01-11 20:23:43 mathomp4 Exp $ 

ALL: build_here

LOCDIR   = src/Infrastructure

include $(ESMF_DIR)/makefile

#TODO: remove the IO/PIO entry below once ESMCI::IO satisfies Array IO needs
DIRS        = stubs Util Base LogErr VM IO/PIO TimeMgr DELayout \
              Config ArraySpec LocalArray Route DistGrid Array ArrayBundle \
              IO Grid Mesh GridUtil LocStream XGrid GeomBase Regrid Field \
              Container FieldBundle Attribute 

CLEANDIRS   =
CLEANFILES  =
CLOBBERDIRS =



