#!/bin/csh

gxps -c -i $3/$1.turbuv.$2.out -o $3/$1.turbuv.$2.ps
gxps -c -i $3/$1.turbtq.$2.out -o $3/$1.turbtq.$2.ps

convert -seed 1 -rotate 90 -density 90x90 $3/$1.turbuv.$2.ps  $3/turbuv.$2.gif
convert -seed 1 -rotate 90 -density 90x90 $3/$1.turbtq.$2.ps  $3/turbtq.$2.gif

/bin/rm    $3/$1.turbuv.$2.out  $3/$1.turbuv.$2.ps
/bin/rm    $3/$1.turbtq.$2.out  $3/$1.turbtq.$2.ps


