#!/bin/sh
# $Id: mpirun,v 1.1.5.1 2013-01-11 20:23:44 mathomp4 Exp $
if [ $1 !=  "-np" ]; then
progname=$*
elif  [ $2 =  "1" ]; then
shift ; shift
progname=$*
else
echo "FAIL:Uniprocessor version of MPI can only use one processor."
exit 1
fi

# If relative path is used prepend a ./
tail=`echo $progname | sed 's/\/.*//'` 
if  [ "$tail" != "" ]; then
  progname="./$progname"
fi

# Execute the program
$progname
exit 0

