# $Id: makefile,v 1.1.5.1 2013-01-11 20:23:43 mathomp4 Exp $ 

LOCDIR   = src

include $(ESMF_DIR)/makefile

DIRS        = prologue test_harness Infrastructure Superstructure epilogue \
              doc system_tests apps addon

CLEANFILES  = 
CLEANDIRS   = 
CLOBBERDIRS = 
MOSTLYCLEANDIRS = Infrastructure Superstructure system_tests test_harness
