  'set grid off'
  'set gxout shaded'
  'black'
  'set gxout contour'
  'set ccolor rainbow'
  'set rbrange 990 1020'
  'set cint 2.0'
* 'set cthick 6'
  'set mpdraw on'
  'set clab  off'
  'set grads off'
  'd slp/100'

  'date 1'

