#!/bin/csh

set name   = $1
set pltdir = $2
set color  = $3

if( .$color == . ) set color = ' '

set file = $pltdir/$name

# Create Postscript from Grads
# ----------------------------
        if( -e $file.out ) then
                gxps $color -i $file.out -o $file.ps
        endif

# Create GIF from Postscript
# --------------------------
        if( -e $file.ps ) then
                convert -seed 1 -rotate 90 -density 90x90 $file.ps $file.gif
        endif

# Remove Intermediate Files
# -------------------------
        if( -e $file.gif ) then
                /bin/rm $file.out $file.ps
        endif
