# $Id: makefile,v 1.1.5.1 2013-01-11 20:23:44 mathomp4 Exp $

ALL:  build_unit_tests
run:  run_unit_tests

LOCDIR	  = src/Infrastructure/Regrid/tests

TESTS_OBJ = 

ESMF_RegridUTest.o:$(TESTS_OBJ)

TESTS_BUILD   = 

TESTS_RUN     = 

TESTS_RUN_UNI =	

include $(ESMF_DIR)/makefile


DIRS =

CLEANDIRS   = 
CLEANFILES  = $(TESTS_BUILD)
CLOBBERDIRS =


