#!/bin/bash

# setBashrc: bash script to set local bashrc symbolic link for use with GCHP
#    
# Arguments: pass full path (no symlinks) to your customized GCHP bashrc
#
# Usage: ./setBashrc.sh /path/to/your/bashrc
#
# E. Lundgren, 10/12/2018

# Prompt the user for bashrc path and set symlink
if [[ -L Bashrc ]]; then
    unlink Bashrc
fi
if [[ -f "$1" ]]; then
  ln -s $1 Bashrc
  file Bashrc
else
  echo "Error: Bashrc file does not exist"
  exit 1
fi


exit 0
