# $Id: makefile,v 1.1.5.1 2013-01-11 20:23:44 mathomp4 Exp $ 

ALL:  build_examples

run: run_examples

LOCDIR	  = src/Infrastructure/Util/examples

EXAMPLES_BUILD = 

EXAMPLES_RUN = 

EXAMPLES_RUN_UNI = 


include $(ESMF_DIR)/makefile

DIRS	  = 

CLEANDIRS   = 
CLEANFILES  = $(EXAMPLES_BUILD)
CLOBBERDIRS =


