#!/bin/csh -f

set nymd = $1
set nhms = $2

set year  = `echo $nymd | cut -b1-4`
set month = `echo $nymd | cut -b5-6`
set hour  = `echo $nhms | cut -b1-2`

#######################################################################
#         Create Strip Utility to Remove Multiple Blank Spaces
#######################################################################

set           FILE = strip
/bin/rm -f   $FILE
cat << EOF > $FILE
#!/bin/ksh
/bin/mv \$1 \$1.tmp
touch   \$1
while read line
do
echo \$line | cut -d'>' -f2- >> \$1
done < \$1.tmp
exit
EOF
chmod +x $FILE

#######################################################################

# Link Original ECMWF.nc File
# ---------------------------
/bin/rm -f ecmwf.data
/bin/ln -s /discover/nobackup/projects/gmao/g6dev/ltakacs/ecmwf/Y$year/M$month/ecmwf.inst3_3d_wxm_Np.${nymd}_${hour}z+${nymd}_${hour}z.nc  ecmwf.data


# Convert Original ECMWF.nc File to GFIO-Readable nc4 File (Creates:  grads.fwrite.nc4)
# -------------------------------------------------------------------------------------
/bin/rm -f                                               grads.commands
touch                                                    grads.commands
echo \'sdfopen ecmwf.data\'                           >> grads.commands
echo \'run $GEOSUTIL/plots/grads_util/writegrads.gs\' >> grads.commands
echo \'q ctlinfo\'                                    >> grads.commands
echo   write \(ctlinfo,\result\)                      >> grads.commands
echo \'quit\'                                         >> grads.commands
grads -b -l -c "run grads.commands"

./strip ctlinfo

$GEOSUTIL/post/flat2hdf.x -flat grads.fwrite -ctl ctlinfo -nymd $nymd -nhms $nhms -ndt 21600
$GEOSUTIL/post/ec_prs2eta.x -ecmwf grads.fwrite.nc4

# Note, this creates:
# ------------------
#   ec_prs2eta.${nymd}_${hour}z.nc4


