#!/bin/csh

      ./configure
source .configure

if(-e makeiau_${ARCH}.x ) /bin/rm makeiau_${ARCH}.x
if(-e test.o            ) /bin/rm test.o
if(-e test.F            ) /bin/rm test.F
cat makeiau.F timer.F gmap.F > test.F

# Set Endian
# ----------
 set ENDIAN = ""
#set ENDIAN = "-convert big_endian"


# Linux Compilation
# -----------------
if( ${ARCH} == 'Linux' ) then

     set gfio = GMAO_gfio_r4
     set cfio = MAPL_cfio_r4
     set hdf  = GMAO_mfhdf3

     ifort -c -extend_source -O -I.     -Dmpi  dynamics_lattice_module.F
     ifort -c -extend_source -O -I.     -Dmpi  mpi_util.F
     ifort -c -extend_source -O -I.     -Dmpi  mymalloc.F
     ifort -c -extend_source -O -I.     -Dmpi  windfix.F
     ifort -c -extend_source -O -I. -r8 -Dmpi  PWSSSP.F

ifort -c -DESMA  -I$BASEDIR/$ARCH/include/esmf $ENDIAN \
         -O3 -assume byterecl  -extend_source -fpe0  -align dcommons -Dmpi -I . test.F

ifort -L$BASEDIR/$ARCH/lib \
      -o makeiau_$ARCH.x test.o dynamics_lattice_module.o mpi_util.o mymalloc.o windfix.o PWSSSP.o \
      -L$GFIODIR/$ARCH/lib \
      -l$cfio -l$gfio -l$hdf \
      -lmfhdf -ldf -ljpeg -lz -lsz -ldl -lc -lrt -lcprts -lunwind -lfmpi -lmpi -lmpio -lesmf

endif

if( -e test.F ) /bin/rm test.F
if( -e test.o ) /bin/rm test.o
