#! /bin/csh -x

set host      = $1
set directory = $2
set filename  = $3
set local     = $4

scp ${host}:${directory}/${filename} ${local}
exit

@ iterations = 3
@ counter    = 1
while ( $counter <= $iterations )
scp ${host}:${directory}/${filename} ${local}

set localsize  = `        ls -la              ${local}    | cut -f 5-5 -d " "`
set remotesize = `ssh lou ls -la ${directory}/${filename} | cut -f 5-5 -d " "`

if( $localsize == $remotesize ) then
   @ counter   =  $iterations + 1
else
   if( $counter == $iterations ) then
        echo scp of ${directory}/${filename} failed!
        exit 1
   endif
   @ counter   =  $counter    + 1
endif

end

