#!/bin/csh 


# Set KEY for finding RESTART Names
# ---------------------------------
@ nmax = $#argv
  if( $nmax == 0 ) then
    set expid = d500_eros_01.
    set key   = _rst.20060104_21z.bin
  else
    set expid = ''
    set key   = $1
  endif


# Check for Executables
# ---------------------
if(! -e swapendian.x     ) cc    -o swapendian.x     swapendian.c
if(! -e swapendian_FV.x  ) ifort -o swapendian_FV.x  swapendian_FV.f90

# Convert FV RESTART
# ------------------
set file = `ls -1 ${expid}*${key} | grep -i fvcore_internal`
    swapendian_FV.x $file $file.swap

# Convert Generic RESTARTS
# ------------------------
set files = `ls -1 ${expid}*${key} | grep -v cap | grep -iv fvcore_internal`

foreach file ( $files )
   set base = `basename $file`
   swapendian.x $file $base.swap
end
