#!/bin/csh

set name   = $1
set anal   = $2
set level  = $3
set season = $4
set pltdir = $5

set file = $pltdir/horiz_${anal}_${name}_$level.$season

# Create Postscript from Grads
# ----------------------------
        if( -e $file.out ) then
                gxps -c -i $file.out -o $file.ps
        endif

# Create GIF from Postscript
# --------------------------
        if( -e $file.ps ) then
                convert -seed 1 -density 90x90 $file.ps $file.gif
        endif

# Remove Intermediate Files
# -------------------------
        if( -e $file.gif ) then
               /bin/rm   $file.out $file.ps
               chmod 644 $file.gif
        endif
