#!/bin/csh

gxps -c -i $3/$1.physuv.$2.out -o $3/$1.physuv.$2.ps
gxps -c -i $3/$1.phystq.$2.out -o $3/$1.phystq.$2.ps

convert -seed 1 -rotate 90 -density 90x90 $3/$1.physuv.$2.ps  $3/physuv.$2.gif
convert -seed 1 -rotate 90 -density 90x90 $3/$1.phystq.$2.ps  $3/phystq.$2.gif

/bin/rm    $3/$1.physuv.$2.out  $3/$1.physuv.$2.ps
/bin/rm    $3/$1.phystq.$2.out  $3/$1.phystq.$2.ps


